import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProjectInvitations1790886507565 implements MigrationInterface {
    name = 'AddProjectInvitations1790886507565'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "fk_projects_created_by"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "fk_projects_leader"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "fk_user_roles_role"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "fk_user_roles_user"`);
        await queryRunner.query(`ALTER TABLE "external_accounts" DROP CONSTRAINT "fk_external_accounts_user"`);
        await queryRunner.query(`ALTER TABLE "project_status_history" DROP CONSTRAINT "fk_psh_changed_by"`);
        await queryRunner.query(`ALTER TABLE "project_status_history" DROP CONSTRAINT "fk_psh_project"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "fk_pm_resource_profile"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "fk_pm_user"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "fk_pm_project"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "fk_tasks_created_by"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "fk_tasks_responsible_user"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "fk_tasks_parent_task"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "fk_tasks_project"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "fk_td_created_by"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "fk_td_successor"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "fk_td_predecessor"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "fk_tags_project"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "fk_task_tags_tag"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "fk_task_tags_task"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "fk_comments_author"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "fk_comments_task"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "fk_costs_created_by"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "fk_costs_category"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "fk_costs_task"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "fk_costs_project"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_cost"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_task"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "fk_budgets_created_by"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "fk_budgets_project"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "fk_budget_items_category"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "fk_budget_items_budget"`);
        await queryRunner.query(`ALTER TABLE "progress_metrics" DROP CONSTRAINT "fk_progress_metrics_project"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "fk_audit_logs_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "fk_notifications_task"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "fk_notifications_project"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "fk_notifications_user"`);
        await queryRunner.query(`ALTER TABLE "ai_conversations" DROP CONSTRAINT "fk_ai_conversations_user"`);
        await queryRunner.query(`ALTER TABLE "ai_messages" DROP CONSTRAINT "fk_ai_messages_conversation"`);
        await queryRunner.query(`ALTER TABLE "project_activities" DROP CONSTRAINT "FK_project_activities_actor_id"`);
        await queryRunner.query(`ALTER TABLE "project_activities" DROP CONSTRAINT "FK_project_activities_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_tasks_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."ux_budgets_one_current_per_project"`);
        await queryRunner.query(`ALTER TABLE "resource_profiles" DROP CONSTRAINT "ck_resource_profiles_hourly_cost_non_negative"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "ck_tasks_estimated_cost_non_negative"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "ck_tasks_actual_cost_non_negative"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "ck_task_dependencies_no_self_reference"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "ck_costs_amount_non_negative"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "ck_attachments_size_non_negative"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "ck_attachments_exactly_one_owner"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "ck_budgets_total_amount_non_negative"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "ck_budgets_version_positive"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "ck_budget_items_amount_non_negative"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" DROP CONSTRAINT "ck_exchange_rates_rate_positive"`);
        await queryRunner.query(`CREATE TABLE "project_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "email" character varying(255) NOT NULL, "project_role" "public"."project_member_role_enum" NOT NULL, "token" character varying(255) NOT NULL, "invited_by" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9ab1815332452b1459164233468" UNIQUE ("token"), CONSTRAINT "PK_bddf504e527c1c64289e2c9cfd8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "estimated_cost"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "actual_cost"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "title" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum" RENAME TO "task_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum" AS ENUM('PENDING', 'BLOCKED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."task_status_enum" USING "status"::"text"::"public"."task_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_cb5ae1474bff68b3e0a68f56869" FOREIGN KEY ("leader_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_accounts" ADD CONSTRAINT "FK_50528d2b5b07136b36ed2954247" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_history" ADD CONSTRAINT "FK_19c81903135d9364ed8b7a77025" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_history" ADD CONSTRAINT "FK_25681df9655976c1c0179b94cdd" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_4f31331ade12ac09aa4fc24abd0" FOREIGN KEY ("resource_profile_id") REFERENCES "resource_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_7c1fcde0ccd62465124df68460c" FOREIGN KEY ("responsible_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_94fc9460c9c76ae5b9c33bb0dbd" FOREIGN KEY ("predecessor_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_8f7ce14b7b1cc27006f623fed16" FOREIGN KEY ("successor_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_4a251b37965df3adc13d3f37ddb" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_7ab852bb0ada09a0fc3adb7e5de" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_70515bc464901781ac60b82a1ea" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_f883135d033e1541f6a81972e7d" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_18c2493067c11f44efb35ca0e03" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_ca96de050d1b690cefccebc7dc8" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_a50536a2697343b2aeff328c041" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_8e78cb1d50f499608c5e452a845" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_d4c6aca3ab653138c4af76a16df" FOREIGN KEY ("cost_category_id") REFERENCES "cost_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_edcba7f916c411baa820c93dd98" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e62fd181b97caa6b150b09220b1" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_5079c0354873123e99f9fa7fc83" FOREIGN KEY ("cost_id") REFERENCES "costs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_ece88bfd72296dfc861b87fff55" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_1fc5f692c5d4a87724d83caf55e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "FK_c3baf040ebaa2c35a6f5e0fe4d9" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "FK_2e0cdb66e00448b06c390e37a28" FOREIGN KEY ("cost_category_id") REFERENCES "cost_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress_metrics" ADD CONSTRAINT "FK_30a0280eb6dce0e3ba60e678394" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_95464140d7dc04d7efb0afd6be0" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_b4a7cd30c9f4ca1b23ef0eb6dd8" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_conversations" ADD CONSTRAINT "FK_12fdbf99ca0da93085d61edd3bb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_messages" ADD CONSTRAINT "FK_de21fcb2d1df7fd6ca70f555b6d" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_activities" ADD CONSTRAINT "FK_da57aaa2cda866acedacc09867f" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_activities" ADD CONSTRAINT "FK_83236a95ddd9e533dcb32940e7b" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_invitations" ADD CONSTRAINT "FK_ff93e974f241ea13e6f7d5aa2d5" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_invitations" ADD CONSTRAINT "FK_1ad3a7cab9985a9974194a4cbba" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project_invitations" DROP CONSTRAINT "FK_1ad3a7cab9985a9974194a4cbba"`);
        await queryRunner.query(`ALTER TABLE "project_invitations" DROP CONSTRAINT "FK_ff93e974f241ea13e6f7d5aa2d5"`);
        await queryRunner.query(`ALTER TABLE "project_activities" DROP CONSTRAINT "FK_83236a95ddd9e533dcb32940e7b"`);
        await queryRunner.query(`ALTER TABLE "project_activities" DROP CONSTRAINT "FK_da57aaa2cda866acedacc09867f"`);
        await queryRunner.query(`ALTER TABLE "ai_messages" DROP CONSTRAINT "FK_de21fcb2d1df7fd6ca70f555b6d"`);
        await queryRunner.query(`ALTER TABLE "ai_conversations" DROP CONSTRAINT "FK_12fdbf99ca0da93085d61edd3bb"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_b4a7cd30c9f4ca1b23ef0eb6dd8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_95464140d7dc04d7efb0afd6be0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "progress_metrics" DROP CONSTRAINT "FK_30a0280eb6dce0e3ba60e678394"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "FK_2e0cdb66e00448b06c390e37a28"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "FK_c3baf040ebaa2c35a6f5e0fe4d9"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_1fc5f692c5d4a87724d83caf55e"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_ece88bfd72296dfc861b87fff55"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_5079c0354873123e99f9fa7fc83"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e62fd181b97caa6b150b09220b1"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_edcba7f916c411baa820c93dd98"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_d4c6aca3ab653138c4af76a16df"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_8e78cb1d50f499608c5e452a845"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_a50536a2697343b2aeff328c041"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_ca96de050d1b690cefccebc7dc8"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_18c2493067c11f44efb35ca0e03"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_f883135d033e1541f6a81972e7d"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_70515bc464901781ac60b82a1ea"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_7ab852bb0ada09a0fc3adb7e5de"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_4a251b37965df3adc13d3f37ddb"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_8f7ce14b7b1cc27006f623fed16"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_94fc9460c9c76ae5b9c33bb0dbd"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_7c1fcde0ccd62465124df68460c"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_4f31331ade12ac09aa4fc24abd0"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "project_status_history" DROP CONSTRAINT "FK_25681df9655976c1c0179b94cdd"`);
        await queryRunner.query(`ALTER TABLE "project_status_history" DROP CONSTRAINT "FK_19c81903135d9364ed8b7a77025"`);
        await queryRunner.query(`ALTER TABLE "external_accounts" DROP CONSTRAINT "FK_50528d2b5b07136b36ed2954247"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_cb5ae1474bff68b3e0a68f56869"`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum_old" AS ENUM('PENDING', 'BLOCKED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'IN_REVIEW')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."task_status_enum_old" USING "status"::"text"::"public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum_old" RENAME TO "task_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "title" character varying(300) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "actual_cost" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "estimated_cost" numeric(14,2)`);
        await queryRunner.query(`DROP TABLE "project_invitations"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ADD CONSTRAINT "ck_exchange_rates_rate_positive" CHECK ((rate > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "ck_budget_items_amount_non_negative" CHECK ((amount >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "ck_budgets_version_positive" CHECK ((version > 0))`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "ck_budgets_total_amount_non_negative" CHECK ((total_amount >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "ck_attachments_exactly_one_owner" CHECK (((((task_id IS NOT NULL))::integer + ((cost_id IS NOT NULL))::integer) = 1))`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "ck_attachments_size_non_negative" CHECK ((size_bytes >= 0))`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "ck_costs_amount_non_negative" CHECK ((amount >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "ck_task_dependencies_no_self_reference" CHECK ((predecessor_task_id <> successor_task_id))`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "ck_tasks_actual_cost_non_negative" CHECK (((actual_cost IS NULL) OR (actual_cost >= (0)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "ck_tasks_estimated_cost_non_negative" CHECK (((estimated_cost IS NULL) OR (estimated_cost >= (0)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "resource_profiles" ADD CONSTRAINT "ck_resource_profiles_hourly_cost_non_negative" CHECK ((hourly_cost >= (0)::numeric))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_budgets_one_current_per_project" ON "budgets" ("project_id") WHERE (is_current = true)`);
        await queryRunner.query(`CREATE INDEX "ix_tasks_due_date" ON "tasks" ("due_date") `);
        await queryRunner.query(`ALTER TABLE "project_activities" ADD CONSTRAINT "FK_project_activities_project_id" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_activities" ADD CONSTRAINT "FK_project_activities_actor_id" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_messages" ADD CONSTRAINT "fk_ai_messages_conversation" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_conversations" ADD CONSTRAINT "fk_ai_conversations_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress_metrics" ADD CONSTRAINT "fk_progress_metrics_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "fk_budget_items_budget" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "fk_budget_items_category" FOREIGN KEY ("cost_category_id") REFERENCES "cost_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "fk_budgets_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "fk_budgets_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_cost" FOREIGN KEY ("cost_id") REFERENCES "costs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "fk_costs_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "fk_costs_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "fk_costs_category" FOREIGN KEY ("cost_category_id") REFERENCES "cost_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "fk_costs_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_author" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "fk_task_tags_task" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "fk_task_tags_tag" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "fk_tags_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "fk_td_predecessor" FOREIGN KEY ("predecessor_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "fk_td_successor" FOREIGN KEY ("successor_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "fk_td_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_parent_task" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_responsible_user" FOREIGN KEY ("responsible_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "fk_tasks_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "fk_pm_resource_profile" FOREIGN KEY ("resource_profile_id") REFERENCES "resource_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_history" ADD CONSTRAINT "fk_psh_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_history" ADD CONSTRAINT "fk_psh_changed_by" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_accounts" ADD CONSTRAINT "fk_external_accounts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_leader" FOREIGN KEY ("leader_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
