import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTasksTable1789920896816 implements MigrationInterface {
    name = 'AddTasksTable1789920896816'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "name" character varying(200) NOT NULL, "avatar_url" character varying(500), "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."project_status_enum" AS ENUM('PLANNED', 'IN_PROGRESS', 'PAUSED', 'FINISHED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "start_date" date, "estimated_end_date" date, "status" "public"."project_status_enum" NOT NULL DEFAULT 'PLANNED', "leader_id" uuid NOT NULL, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "archived_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_projects_status" ON "projects" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."role_name_enum" AS ENUM('ADMIN', 'PROGRAM_MANAGER', 'PROJECT_LEADER', 'COLLABORATOR', 'OBSERVER')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."role_name_enum" NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_user_roles_user_role" ON "user_roles" ("user_id", "role_id") `);
        await queryRunner.query(`CREATE TYPE "public"."external_account_provider_enum" AS ENUM('GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "external_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" "public"."external_account_provider_enum" NOT NULL, "provider_subject" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_48de4cf673dd62798b19df4f7bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_external_accounts_user_id" ON "external_accounts" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_external_accounts_provider_subject" ON "external_accounts" ("provider", "provider_subject") `);
        await queryRunner.query(`CREATE TABLE "authorized_domains" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "domain" character varying(255) NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_42cd19be1466053c7c343af73c1" UNIQUE ("domain"), CONSTRAINT "PK_13988795deaf0578cb24ea61ace" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_status_enum" AS ENUM('PLANNED', 'IN_PROGRESS', 'PAUSED', 'FINISHED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "project_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "previous_status" "public"."project_status_enum", "new_status" "public"."project_status_enum" NOT NULL, "changed_by_user_id" uuid NOT NULL, "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_97d27898a32d73f93930dd394d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_project_status_history_project_id" ON "project_status_history" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "resource_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "hourly_cost" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4fdadaa3617289150f0aaa69a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "project_role" character varying(100) NOT NULL, "resource_profile_id" uuid, "estimated_hours" numeric(8,2), "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "removed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_project_members_project_id" ON "project_members" ("project_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_project_members_project_user" ON "project_members" ("project_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum" AS ENUM('PENDING', 'BLOCKED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."task_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "parent_task_id" uuid, "title" character varying(300) NOT NULL, "description" text, "responsible_user_id" uuid, "status" "public"."task_status_enum" NOT NULL DEFAULT 'PENDING', "priority" "public"."task_priority_enum" NOT NULL DEFAULT 'MEDIUM', "planned_start_date" date, "due_date" date, "estimated_cost" numeric(14,2), "actual_cost" numeric(14,2), "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_tasks_project_id" ON "tasks" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "ix_tasks_parent_task_id" ON "tasks" ("parent_task_id") `);
        await queryRunner.query(`CREATE INDEX "ix_tasks_responsible_user_id" ON "tasks" ("responsible_user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_tasks_status" ON "tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "ix_tasks_due_date" ON "tasks" ("due_date") `);
        await queryRunner.query(`CREATE TYPE "public"."dependency_type_enum" AS ENUM('FINISH_START', 'START_START', 'FINISH_FINISH', 'START_FINISH')`);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "predecessor_task_id" uuid NOT NULL, "successor_task_id" uuid NOT NULL, "dependency_type" "public"."dependency_type_enum" NOT NULL DEFAULT 'FINISH_START', "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e31de0e173af595a21c4ec8e48b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_task_dependencies_unique" ON "task_dependencies" ("predecessor_task_id", "successor_task_id", "dependency_type") `);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_tags_project_name" ON "tags" ("project_id", "name") `);
        await queryRunner.query(`CREATE TABLE "task_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "tag_id" uuid NOT NULL, CONSTRAINT "PK_7b47a7628547c0976415988d3cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_task_tags_task_tag" ON "task_tags" ("task_id", "tag_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "author_user_id" uuid NOT NULL, "content" text NOT NULL, "edited_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_comments_task_id" ON "comments" ("task_id") `);
        await queryRunner.query(`CREATE TABLE "cost_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b117ea4e8659b8a4dde002f8a6a" UNIQUE ("name"), CONSTRAINT "PK_7a64898fa80f0cd6ec029d227d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "costs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "task_id" uuid, "cost_category_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "currency" character varying(3) NOT NULL, "cost_date" date NOT NULL, "description" text, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_05cc8aa05396a72553cdff6d5be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_costs_project_id" ON "costs" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid, "cost_id" uuid, "file_name" character varying(300) NOT NULL, "storage_path" character varying(1000) NOT NULL, "mime_type" character varying(150) NOT NULL, "size_bytes" bigint NOT NULL, "uploaded_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "total_amount" numeric(14,2) NOT NULL, "currency" character varying(3) NOT NULL, "version" integer NOT NULL, "approved_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid NOT NULL, "is_current" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_budgets_project_version" ON "budgets" ("project_id", "version") `);
        await queryRunner.query(`CREATE TABLE "budget_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "budget_id" uuid NOT NULL, "cost_category_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9eb705f406c83a1167ef575cd7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_budget_items_budget_category" ON "budget_items" ("budget_id", "cost_category_id") `);
        await queryRunner.query(`CREATE TABLE "exchange_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from_currency" character varying(3) NOT NULL, "to_currency" character varying(3) NOT NULL, "rate" numeric(18,6) NOT NULL, "effective_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_33a614bad9e61956079d817ebe2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_exchange_rates_pair_date" ON "exchange_rates" ("from_currency", "to_currency", "effective_date") `);
        await queryRunner.query(`CREATE TABLE "progress_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "measured_at" TIMESTAMP WITH TIME ZONE NOT NULL, "actual_progress" numeric(5,2) NOT NULL, "expected_progress" numeric(5,2), "deviation" numeric(5,2), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f5cd72da8068987c3de6abc007e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_progress_metrics_project_measured_at" ON "progress_metrics" ("project_id", "measured_at") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_entity_type_enum" AS ENUM('TASK', 'PROJECT', 'BUDGET', 'COST')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_origin_enum" AS ENUM('UI', 'AI', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_type" "public"."audit_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "action" character varying(50) NOT NULL, "user_id" uuid, "origin" "public"."audit_origin_enum" NOT NULL DEFAULT 'SYSTEM', "old_values" jsonb, "new_values" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_channel_enum" AS ENUM('IN_APP', 'EMAIL')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "project_id" uuid, "task_id" uuid, "type" character varying(50) NOT NULL, "channel" "public"."notification_channel_enum" NOT NULL DEFAULT 'IN_APP', "title" character varying(200) NOT NULL, "message" text NOT NULL, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "ai_conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "total_input_tokens" integer NOT NULL DEFAULT '0', "total_output_tokens" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_60db12765b82858ba00c8aa4ae2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ai_message_role_enum" AS ENUM('USER', 'ASSISTANT', 'TOOL', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "ai_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "role" "public"."ai_message_role_enum" NOT NULL, "content" text NOT NULL, "input_tokens" integer, "output_tokens" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a390434d4a515ba18a41bc996c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ai_messages_conversation_id" ON "ai_messages" ("conversation_id") `);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_cb5ae1474bff68b3e0a68f56869" FOREIGN KEY ("leader_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_accounts" ADD CONSTRAINT "FK_50528d2b5b07136b36ed2954247" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_history" ADD CONSTRAINT "FK_19c81903135d9364ed8b7a77025" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_history" ADD CONSTRAINT "FK_25681df9655976c1c0179b94cdd" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_4f31331ade12ac09aa4fc24abd0" FOREIGN KEY ("resource_profile_id") REFERENCES "resource_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_7c1fcde0ccd62465124df68460c" FOREIGN KEY ("responsible_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_94fc9460c9c76ae5b9c33bb0dbd" FOREIGN KEY ("predecessor_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_8f7ce14b7b1cc27006f623fed16" FOREIGN KEY ("successor_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_4a251b37965df3adc13d3f37ddb" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_7ab852bb0ada09a0fc3adb7e5de" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_70515bc464901781ac60b82a1ea" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_f883135d033e1541f6a81972e7d" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_18c2493067c11f44efb35ca0e03" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_ca96de050d1b690cefccebc7dc8" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_a50536a2697343b2aeff328c041" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_8e78cb1d50f499608c5e452a845" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_d4c6aca3ab653138c4af76a16df" FOREIGN KEY ("cost_category_id") REFERENCES "cost_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "costs" ADD CONSTRAINT "FK_edcba7f916c411baa820c93dd98" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e62fd181b97caa6b150b09220b1" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_5079c0354873123e99f9fa7fc83" FOREIGN KEY ("cost_id") REFERENCES "costs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_ece88bfd72296dfc861b87fff55" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_1fc5f692c5d4a87724d83caf55e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "FK_c3baf040ebaa2c35a6f5e0fe4d9" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_items" ADD CONSTRAINT "FK_2e0cdb66e00448b06c390e37a28" FOREIGN KEY ("cost_category_id") REFERENCES "cost_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress_metrics" ADD CONSTRAINT "FK_30a0280eb6dce0e3ba60e678394" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_95464140d7dc04d7efb0afd6be0" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_b4a7cd30c9f4ca1b23ef0eb6dd8" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_conversations" ADD CONSTRAINT "FK_12fdbf99ca0da93085d61edd3bb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_messages" ADD CONSTRAINT "FK_de21fcb2d1df7fd6ca70f555b6d" FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_messages" DROP CONSTRAINT "FK_de21fcb2d1df7fd6ca70f555b6d"`);
        await queryRunner.query(`ALTER TABLE "ai_conversations" DROP CONSTRAINT "FK_12fdbf99ca0da93085d61edd3bb"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_b4a7cd30c9f4ca1b23ef0eb6dd8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_95464140d7dc04d7efb0afd6be0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "progress_metrics" DROP CONSTRAINT "FK_30a0280eb6dce0e3ba60e678394"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "FK_2e0cdb66e00448b06c390e37a28"`);
        await queryRunner.query(`ALTER TABLE "budget_items" DROP CONSTRAINT "FK_c3baf040ebaa2c35a6f5e0fe4d9"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_1fc5f692c5d4a87724d83caf55e"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_ece88bfd72296dfc861b87fff55"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_5079c0354873123e99f9fa7fc83"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e62fd181b97caa6b150b09220b1"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_edcba7f916c411baa820c93dd98"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_d4c6aca3ab653138c4af76a16df"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_8e78cb1d50f499608c5e452a845"`);
        await queryRunner.query(`ALTER TABLE "costs" DROP CONSTRAINT "FK_a50536a2697343b2aeff328c041"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_ca96de050d1b690cefccebc7dc8"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_18c2493067c11f44efb35ca0e03"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_f883135d033e1541f6a81972e7d"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_70515bc464901781ac60b82a1ea"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_7ab852bb0ada09a0fc3adb7e5de"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_4a251b37965df3adc13d3f37ddb"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_8f7ce14b7b1cc27006f623fed16"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_94fc9460c9c76ae5b9c33bb0dbd"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_7c1fcde0ccd62465124df68460c"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_4f31331ade12ac09aa4fc24abd0"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "project_status_history" DROP CONSTRAINT "FK_25681df9655976c1c0179b94cdd"`);
        await queryRunner.query(`ALTER TABLE "project_status_history" DROP CONSTRAINT "FK_19c81903135d9364ed8b7a77025"`);
        await queryRunner.query(`ALTER TABLE "external_accounts" DROP CONSTRAINT "FK_50528d2b5b07136b36ed2954247"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_cb5ae1474bff68b3e0a68f56869"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ai_messages_conversation_id"`);
        await queryRunner.query(`DROP TABLE "ai_messages"`);
        await queryRunner.query(`DROP TYPE "public"."ai_message_role_enum"`);
        await queryRunner.query(`DROP TABLE "ai_conversations"`);
        await queryRunner.query(`DROP INDEX "public"."ix_notifications_user_id"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notification_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_audit_logs_entity"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_origin_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_progress_metrics_project_measured_at"`);
        await queryRunner.query(`DROP TABLE "progress_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."ux_exchange_rates_pair_date"`);
        await queryRunner.query(`DROP TABLE "exchange_rates"`);
        await queryRunner.query(`DROP INDEX "public"."ux_budget_items_budget_category"`);
        await queryRunner.query(`DROP TABLE "budget_items"`);
        await queryRunner.query(`DROP INDEX "public"."ux_budgets_project_version"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP INDEX "public"."ix_costs_project_id"`);
        await queryRunner.query(`DROP TABLE "costs"`);
        await queryRunner.query(`DROP TABLE "cost_categories"`);
        await queryRunner.query(`DROP INDEX "public"."ix_comments_task_id"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."ux_task_tags_task_tag"`);
        await queryRunner.query(`DROP TABLE "task_tags"`);
        await queryRunner.query(`DROP INDEX "public"."ux_tags_project_name"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP INDEX "public"."ux_task_dependencies_unique"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`DROP TYPE "public"."dependency_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_tasks_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."ix_tasks_status"`);
        await queryRunner.query(`DROP INDEX "public"."ix_tasks_responsible_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_tasks_parent_task_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_tasks_project_id"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."task_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ux_project_members_project_user"`);
        await queryRunner.query(`DROP INDEX "public"."ix_project_members_project_id"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP TABLE "resource_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."ix_project_status_history_project_id"`);
        await queryRunner.query(`DROP TABLE "project_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."project_status_enum"`);
        await queryRunner.query(`DROP TABLE "authorized_domains"`);
        await queryRunner.query(`DROP INDEX "public"."ux_external_accounts_provider_subject"`);
        await queryRunner.query(`DROP INDEX "public"."ix_external_accounts_user_id"`);
        await queryRunner.query(`DROP TABLE "external_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."external_account_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ux_user_roles_user_role"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."role_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_projects_status"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."project_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ux_users_email"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
